"""
Seed data definitions for all 66 Python tutorials across Beginner, Intermediate, and Advanced tiers.
"""

from django.utils.text import slugify
from tutorials.models import TutorialCategory, Tutorial

def seed_tutorials():
    print("Seeding Tutorials (66 topics)...")

    # ==========================================
    # 1. BEGINNER LEVEL CATEGORIES & TOPICS
    # ==========================================
    cat_beg_intro, _ = TutorialCategory.objects.get_or_create(
        slug='python-basics',
        defaults={'name': 'Python Basics & Setup', 'level': 'beginner', 'order': 1, 'icon': 'fa-play', 'description': 'Get started with Python syntax, installation, and environment setup.'}
    )
    cat_beg_types, _ = TutorialCategory.objects.get_or_create(
        slug='variables-and-data-types',
        defaults={'name': 'Variables & Data Types', 'level': 'beginner', 'order': 2, 'icon': 'fa-cube', 'description': 'Master Python values, dynamic typing, numbers, strings, and operators.'}
    )
    cat_beg_control, _ = TutorialCategory.objects.get_or_create(
        slug='control-flow',
        defaults={'name': 'Control Flow & Conditionals', 'level': 'beginner', 'order': 3, 'icon': 'fa-shuffle', 'description': 'Make decisions with if, elif, else and logical branching.'}
    )
    cat_beg_loops, _ = TutorialCategory.objects.get_or_create(
        slug='loops-and-iterations',
        defaults={'name': 'Loops & Iterations', 'level': 'beginner', 'order': 4, 'icon': 'fa-repeat', 'description': 'Automate repeated tasks with for and while loops, break, continue, and pass.'}
    )
    cat_beg_data_structs, _ = TutorialCategory.objects.get_or_create(
        slug='core-collections',
        defaults={'name': 'Core Data Collections', 'level': 'beginner', 'order': 5, 'icon': 'fa-layer-group', 'description': 'Store and organize data with lists, tuples, sets, and dictionaries.'}
    )
    cat_beg_functions, _ = TutorialCategory.objects.get_or_create(
        slug='functions-basics',
        defaults={'name': 'Functions & Lambdas', 'level': 'beginner', 'order': 6, 'icon': 'fa-gears', 'description': 'Write clean, reusable, modular code with functions and scope rules.'}
    )

    beginner_topics = [
        # Intro
        (cat_beg_intro, "Introduction to Python", "introduction-to-python", 1,
         "Python is a high-level, interpreted, general-purpose programming language renowned for its readability and versatility.",
         "Python was created by Guido van Rossum and released in 1991. It emphasizes code readability with its distinctive use of significant indentation. Python is widely used in web development, data science, machine learning, automation, and DevOps.",
         "# Python code executes line by line via the interpreter\nprint('Hello, Python!')",
         "print('Hello, Python! Welcome to programming.')",
         "Hello, Python! Welcome to programming.",
         "Python is dynamically typed and garbage collected.",
         "Forgetting proper indentation or mixing tabs and spaces.",
         "Automating file backups or analyzing spreadsheet data.",
         "message = 'Hello World'\nprint(message)"),

        (cat_beg_intro, "Installing Python", "installing-python", 2,
         "How to download, install, and verify Python 3 and pip on Windows, macOS, and Linux systems.",
         "Visit python.org/downloads to download Python 3. On Windows, always check the box 'Add python.exe to PATH' during installation. Verify the installation using your command line terminal.",
         "python --version\npip --version",
         "import sys\nprint('Python version:', sys.version_info.major, sys.version_info.minor)",
         "Python version: 3 12",
         "Make sure to use Python 3.x rather than legacy Python 2.",
         "Not checking 'Add to PATH' on Windows, which causes 'python is not recognized' errors.",
         "Setting up development environments for enterprise applications.",
         "import platform\nprint('System Platform:', platform.system())"),

        (cat_beg_intro, "Python Syntax", "python-syntax", 3,
         "Understand statements, indentation, comments, and the Zen of Python.",
         "Unlike languages that use curly braces {} or semicolons ;, Python uses whitespace indentation to define code blocks (functions, loops, classes). 4 spaces per indentation level is the universal PEP 8 standard.",
         "# Single line comment\nif True:\n    # Indented block (4 spaces)\n    pass",
         "x = 5\nif x > 0:\n    print('x is positive')\n    print('Indented code runs together')",
         "x is positive\nIndented code runs together",
         "Never mix tabs and spaces in Python 3.",
         "IndentationError: unexpected indent.",
         "Writing readable code in shared software engineering teams.",
         "if True:\n    print('Indentation is Python\\'s superpower!')"),

        # Variables & Types
        (cat_beg_types, "Variables", "variables", 4,
         "Variables in Python are named references pointing to objects in memory.",
         "Variables do not require explicit type declarations. A variable is created the moment you first assign a value to it using the assignment operator (=).",
         "variable_name = value",
         "name = 'Gowtham'\nage = 25\nheight = 5.9\nis_developer = True\n\nprint(name)\nprint(age)\nprint('Height:', height)\nprint('Developer status:', is_developer)",
         "Gowtham\n25\nHeight: 5.9\nDeveloper status: True",
         "Variable names must start with a letter or underscore, and are case-sensitive.",
         "Using Python reserved keywords (like def, class, if) as variable names.",
         "Storing user credentials, session state, and shopping cart values.",
         "product = 'Laptop'\nprice = 899.99\nprint(f'{product} costs ${price}')"),

        (cat_beg_types, "Data Types", "data-types", 5,
         "Explore Python's built-in core data types and type introspection.",
         "Python provides int, float, str, bool, list, tuple, dict, and set. Use the built-in type() function to determine the data type of any object.",
         "type(variable)",
         "items = [42, 3.1415, 'Coding', True, [1, 2], {'a': 1}]\nfor item in items:\n    print(f'{item!r:15} -> {type(item).__name__}')",
         "42              -> int\n3.1415          -> float\n'Coding'        -> str\nTrue            -> bool\n[1, 2]          -> list\n{'a': 1}        -> dict",
         "Everything in Python is an object, including basic data types and functions.",
         "Assuming types cannot change; Python is dynamic, so a variable can reference different types over time.",
         "Data sanitation and type verification when parsing incoming API payloads.",
         "data = '100'\nprint('Before conversion:', type(data))\nnum = int(data)\nprint('After conversion:', type(num))"),

        (cat_beg_types, "Numbers", "numbers", 6,
         "Integers, floating-point numbers, complex numbers, and arithmetic operations.",
         "Python supports integers with arbitrary precision (limited only by machine memory), IEEE-754 64-bit floats, and complex numbers (1 + 2j).",
         "int_num = 10\nfloat_num = 10.5\ncomplex_num = 2 + 3j",
         "a = 15\nb = 4\nprint('Addition:', a + b)\nprint('Division:', a / b)\nprint('Floor division:', a // b)\nprint('Modulus (remainder):', a % b)\nprint('Exponentiation:', a ** b)",
         "Addition: 19\nDivision: 3.75\nFloor division: 3\nModulus (remainder): 3\nExponentiation: 50625",
         "Float division (/) always returns a float even when dividing integers evenly (4 / 2 = 2.0).",
         "Precision limitations in floats (0.1 + 0.2 == 0.30000000000000004); use the decimal module for financial calculations.",
         "Calculating discounts, tax percentages, and physics simulations.",
         "radius = 5\narea = 3.14159 * (radius ** 2)\nprint('Circle area:', area)"),

        (cat_beg_types, "Strings", "strings", 7,
         "String creation, slicing, formatting with f-strings, and string methods.",
         "Strings in Python are immutable sequences of Unicode characters. They can be enclosed in single, double, or triple quotes. Modern Python uses f-strings for string formatting.",
         "s = 'Hello'\nf_string = f'{variable}'\nslice = s[start:end:step]",
         "text = 'Python Programming'\nprint('Length:', len(text))\nprint('Uppercase:', text.upper())\nprint('Substring [0:6]:', text[0:6])\nprint('Reversed:', text[::-1])\nprint('Replaced:', text.replace('Python', 'Modern Python'))",
         "Length: 18\nUppercase: PYTHON PROGRAMMING\nSubstring [0:6]: Python\nReversed: gnimmargorP nohtyP\nReplaced: Modern Python Programming",
         "Strings are immutable; modifying methods return new string instances.",
         "Attempting to modify string characters by index (e.g. s[0] = 'X' causes TypeError).",
         "Parsing emails, processing CSV file headers, building customer notification templates.",
         "name = 'Alice'\nscore = 98\nprint(f'Congratulations {name}! You scored {score}%.')"),

        (cat_beg_types, "Boolean", "boolean", 8,
         "Booleans represent truth values: True or False, and truthiness in Python.",
         "Booleans are a subclass of integers (True == 1 and False == 0). Any object in Python can be evaluated in a boolean context for 'truthiness'.",
         "flag = True\nis_valid = bool(expression)",
         "print(bool(1))       # True\nprint(bool(0))       # False\nprint(bool(''))      # False (empty string)\nprint(bool('hello')) # True\nprint(bool([]))      # False (empty list)\nprint(bool([1, 2]))  # True",
         "True\nFalse\nFalse\nTrue\nFalse\nTrue",
         "None, 0, 0.0, '', [], (), {}, and set() all evaluate to False.",
         "Comparing booleans with == True rather than writing if condition:.",
         "Authentication flags, feature toggles, and form validation states.",
         "cart = ['Book']\nif cart:\n    print('Cart has items!')"),

        (cat_beg_types, "Operators", "operators", 9,
         "Arithmetic, comparison, logical, assignment, identity, and membership operators.",
         "Python provides arithmetic (+, -, *, /, //, %, **), comparison (==, !=, <, >, <=, >=), logical (and, or, not), identity (is, is not), and membership (in, not in) operators.",
         "a == b\nx in collection\nis_admin and is_active",
         "numbers = [1, 2, 3, 4, 5]\nprint('Is 3 in numbers?', 3 in numbers)\nprint('Is 10 not in numbers?', 10 not in numbers)\na = [1, 2]\nb = [1, 2]\nprint('a == b (value match):', a == b)\nprint('a is b (same memory identity):', a is b)",
         "Is 3 in numbers? True\nIs 10 not in numbers? True\na == b (value match): True\na is b (same memory identity): False",
         "Use '==' for value equality and 'is' for object identity (e.g. x is None).",
         "Using 'is' to compare numbers or strings, which can yield unpredictable caching effects.",
         "Filtering query results and evaluating complex business logic expressions.",
         "age = 20\nhas_id = True\ncan_enter = age >= 18 and has_id\nprint('Eligible to enter:', can_enter)"),

        (cat_beg_types, "Input and Output", "input-and-output", 10,
         "Interacting with users using input() and formatting output with print().",
         "The input() function reads user input from the console as a string. print() displays output and supports custom separators (sep) and line endings (end).",
         "user_input = input('Prompt: ')\nprint(*objects, sep=' ', end='\\n')",
         "print('Python', 'Django', 'FastAPI', sep=' -> ')\nprint('First line', end='... ')\nprint('continuation on same line')\n# Simulating input parsing\nraw_age = '25'\nage = int(raw_age)\nprint(f'In 5 years you will be: {age + 5}')",
         "Python -> Django -> FastAPI\nFirst line... continuation on same line\nIn 5 years you will be: 30",
         "input() always returns a str; convert using int() or float() for numerical operations.",
         "Trying to perform mathematical operations directly on input() without casting.",
         "Building interactive CLI developer utilities and chatbots.",
         "user_name = 'Gowtham'\nprint(f'Welcome aboard, {user_name}!')"),

        # Control flow
        (cat_beg_control, "Conditional Statements", "conditional-statements", 11,
         "Overview of decision-making and boolean logic branching in Python.",
         "Conditional statements evaluate boolean conditions to determine whether a block of statements executes.",
         "if condition:\n    execute_code()",
         "grade = 85\nif grade >= 70:\n    print('Status: Passed with distinction')\nelse:\n    print('Status: Needs improvement')",
         "Status: Passed with distinction",
         "Code within conditions must be consistently indented.",
         "Using assignment (=) instead of comparison (==) in conditions.",
         "Determining user permissions on dashboard routes.",
         "is_authenticated = True\nif is_authenticated:\n    print('Access granted')"),

        (cat_beg_control, "if", "if-statement", 12,
         "The foundation of decision making: the single 'if' statement.",
         "The 'if' keyword checks a condition. If the condition evaluates to True, the nested block of code runs.",
         "if <condition>:\n    <statements>",
         "temperature = 32\nif temperature > 30:\n    print('It is a hot sunny day!')\n    print('Remember to stay hydrated.')",
         "It is a hot sunny day!\nRemember to stay hydrated.",
         "Conditions do not need parentheses in Python, unlike Java or C++.",
         "Omitting the colon (:) at the end of the if line.",
         "Triggering alert notifications when server CPU exceeds 90%.",
         "score = 100\nif score == 100:\n    print('Perfect score!')"),

        (cat_beg_control, "elif", "elif-statement", 13,
         "Evaluate multiple conditions sequentially using 'elif' (short for else if).",
         "The elif clause allows checking multiple mutually exclusive conditions. As soon as one condition evaluates to True, Python executes its block and skips the rest.",
         "if cond1:\n    ...\nelif cond2:\n    ...",
         "score = 78\nif score >= 90:\n    grade = 'A'\nelif score >= 80:\n    grade = 'B'\nelif score >= 70:\n    grade = 'C'\nelif score >= 60:\n    grade = 'D'\nelse:\n    grade = 'F'\nprint(f'Score: {score} -> Grade: {grade}')",
         "Score: 78 -> Grade: C",
         "elif blocks must follow an if statement and precede the optional else clause.",
         "Writing multiple independent if statements when conditions are mutually exclusive.",
         "Tier-based pricing discounts based on cart volume.",
         "hour = 14\nif hour < 12:\n    print('Good morning')\nelif hour < 18:\n    print('Good afternoon')\nelse:\n    print('Good evening')"),

        (cat_beg_control, "else", "else-statement", 14,
         "The catch-all branch that executes when all previous conditions evaluate to False.",
         "The else statement is the final clause of a conditional chain. It executes if neither the initial if nor any elif conditions were met.",
         "if cond:\n    ...\nelse:\n    ...",
         "number = 17\nif number % 2 == 0:\n    print(f'{number} is Even')\nelse:\n    print(f'{number} is Odd')",
         "17 is Odd",
         "The else block is optional and does not take any condition expression.",
         "Attempting to write else (condition): which causes a SyntaxError.",
         "Fallback error messages when an item cannot be found in database.",
         "is_member = False\nif is_member:\n    print('Member discount applied!')\nelse:\n    print('Standard pricing applied.')"),

        # Loops
        (cat_beg_loops, "for Loop", "for-loop", 15,
         "Iterate over sequences (lists, strings, tuples, dictionaries, ranges).",
         "Python's for loop operates as a 'for-each' iterator. It visits each element in an iterable object directly.",
         "for item in iterable:\n    statements",
         "fruits = ['apple', 'banana', 'cherry']\nfor fruit in fruits:\n    print('I like', fruit)\n\nprint('\\nRange iteration:')\nfor i in range(1, 4):\n    print(f'Count: {i}')",
         "I like apple\nI like banana\nI like cherry\n\nRange iteration:\nCount: 1\nCount: 2\nCount: 3",
         "Use enumerate() when you need both the index and the value in a loop.",
         "Modifying a list while iterating over it, causing skipped elements.",
         "Processing batch transactions from database queries.",
         "for i in range(3):\n    print(f'Iteration #{i + 1}')"),

        (cat_beg_loops, "while Loop", "while-loop", 16,
         "Repeatedly execute a block of code as long as a condition remains True.",
         "A while loop tests a condition before each cycle. It is used when the number of iterations is not known in advance.",
         "while condition:\n    statements",
         "countdown = 3\nwhile countdown > 0:\n    print(f'T-minus {countdown}...')\n    countdown -= 1\nprint('Blast off! 🚀')",
         "T-minus 3...\nT-minus 2...\nT-minus 1...\nBlast off! 🚀",
         "Always ensure the loop condition will eventually become False to avoid infinite loops.",
         "Forgetting to update the loop counter variable inside the loop body.",
         "Polling background jobs until completed or timeout reached.",
         "count = 1\nwhile count <= 3:\n    print('Step', count)\n    count += 1"),

        (cat_beg_loops, "break", "break-statement", 17,
         "Prematurely exit from the nearest enclosing loop.",
         "The break statement immediately terminates loop execution. Control flows to the statement following the loop.",
         "while True:\n    if condition:\n        break",
         "numbers = [10, 25, 42, 60, 99]\ntarget = 42\nfor num in numbers:\n    if num == target:\n        print(f'Found target {target}! Stopping search.')\n        break\n    print('Checked:', num)",
         "Checked: 10\nChecked: 25\nFound target 42! Stopping search.",
         "When nested loops exist, break only exits the innermost loop.",
         "Expecting break to exit multiple levels of nested loops at once.",
         "Stopping an API pagination loop once the matching record is discovered.",
         "for n in range(10):\n    if n == 3:\n        break\n    print(n)"),

        (cat_beg_loops, "continue", "continue-statement", 18,
         "Skip the remainder of the current loop iteration and advance to the next.",
         "The continue statement skips the remaining lines of the current iteration and jumps directly to the loop condition or next sequence item.",
         "for item in seq:\n    if skip_condition:\n        continue",
         "for i in range(1, 6):\n    if i == 3:\n        print('Skipping 3!')\n        continue\n    print('Value:', i)",
         "Value: 1\nValue: 2\nSkipping 3!\nValue: 4\nValue: 5",
         "continue helps avoid deeply nested if conditions inside loops.",
         "Placing continue after the statements you intended to skip.",
         "Skipping corrupted rows or blank lines when reading large datasets.",
         "for x in [1, 2, 3, 4, 5]:\n    if x % 2 == 0:\n        continue\n    print('Odd:', x)"),

        (cat_beg_loops, "pass", "pass-statement", 19,
         "The null statement placeholder used where syntax requires a statement but no action is needed.",
         "Python syntax does not allow empty code blocks. The pass keyword serves as a syntactic no-op placeholder during development.",
         "def placeholder_func():\n    pass",
         "def upcoming_feature():\n    # TODO: Implement in sprint 2\n    pass\n\nfor i in range(3):\n    if i == 1:\n        pass  # Do nothing for 1\n    print('Processed item', i)",
         "Processed item 0\nProcessed item 1\nProcessed item 2",
         "pass does absolutely nothing at runtime; it is purely a syntactic placeholder.",
         "Using pass when you intended to use continue or return.",
         "Scaffolding API endpoints and interface definitions during architectural planning.",
         "class TemporaryStub:\n    pass\nprint('Class stub created successfully')"),

        # Core collections
        (cat_beg_data_structs, "Lists", "lists", 20,
         "Mutable, ordered sequences that store heterogeneous items.",
         "Lists are created with brackets []. They support indexing, slicing, appending, inserting, popping, and sorting.",
         "my_list = [item1, item2]\nmy_list.append(item3)",
         "tasks = ['Learn Python', 'Build Project']\ntasks.append('Deploy App')\ntasks.insert(1, 'Practice Exercises')\nprint('Tasks count:', len(tasks))\nprint('Second task:', tasks[1])\nprint('All tasks:', tasks)",
         "Tasks count: 4\nSecond task: Practice Exercises\nAll tasks: ['Learn Python', 'Practice Exercises', 'Build Project', 'Deploy App']",
         "Lists are mutable; methods like .sort() and .reverse() modify the list in place.",
         "Confusing list.append(x) (returns None) with list concatenation (+).",
         "Managing active users in a lobby or shopping cart line items.",
         "items = [3, 1, 2]\nitems.sort()\nprint('Sorted:', items)"),

        (cat_beg_data_structs, "Tuples", "tuples", 21,
         "Immutable, ordered sequences of Python objects.",
         "Tuples are defined using parentheses (). Once created, their items cannot be modified, added, or removed. They are hashable and faster than lists.",
         "point = (x, y)\na, b = (1, 2)  # unpacking",
         "point = (10, 25)\nprint('Point coordinates:', point)\nx, y = point  # Tuple unpacking\nprint(f'X: {x}, Y: {y}')\n# Tuples can be dictionary keys\nlocations = { (40.7128, -74.0060): 'New York City' }\nprint('City:', locations[(40.7128, -74.0060)])",
         "Point coordinates: (10, 25)\nX: 10, Y: 25\nCity: New York City",
         "A single-element tuple requires a trailing comma: (42,).",
         "Attempting to modify a tuple: t[0] = 5 raises TypeError.",
         "Returning multiple related values from a function.",
         "coords = (100, 200)\nprint('X:', coords[0])"),

        (cat_beg_data_structs, "Sets", "sets", 22,
         "Unordered collections of unique elements with mathematical set operations.",
         "Sets are defined using curly braces {} or set(). They automatically deduplicate items and offer O(1) membership lookup.",
         "s = {1, 2, 3}\ns.add(4)",
         "a = {1, 2, 3, 4}\nb = {3, 4, 5, 6}\nprint('Union (a | b):', a | b)\nprint('Intersection (a & b):', a & b)\nprint('Difference (a - b):', a - b)\nraw = ['apple', 'orange', 'apple', 'banana', 'orange']\nprint('Deduplicated:', sorted(list(set(raw))))",
         "Union (a | b): {1, 2, 3, 4, 5, 6}\nIntersection (a & b): {3, 4}\nDifference (a - b): {1, 2}\nDeduplicated: ['apple', 'banana', 'orange']",
         "Set items must be immutable (hashable). Lists cannot be elements of a set.",
         "Creating an empty set with {} creates an empty dict; use set() instead.",
         "Finding common friends between users on social networks.",
         "skills = {'python', 'django', 'python'}\nprint(skills)"),

        (cat_beg_data_structs, "Dictionaries", "dictionaries", 23,
         "Key-value mappings providing fast lookups and intuitive data modeling.",
         "Dictionaries store key-value pairs. Keys must be unique and immutable. Dictionaries maintain insertion order in Python 3.7+.",
         "d = {'key': 'value'}\nvalue = d.get('key', default)",
         "user = {'username': 'gowtham', 'role': 'engineer', 'level': 3}\nuser['xp'] = 450\nprint('Username:', user['username'])\nprint('Non-existent key with default:', user.get('email', 'N/A'))\nprint('All keys:', list(user.keys()))",
         "Username: gowtham\nNon-existent key with default: N/A\nAll keys: ['username', 'role', 'level', 'xp']",
         "Use .get(key) to avoid KeyError when accessing optional dictionary fields.",
         "Modifying a dictionary while iterating over its keys without using list(d.keys()).",
         "JSON configurations, API request bodies, user profile records.",
         "book = {'title': 'Clean Code', 'author': 'Robert Martin'}\nprint(book['title'])"),

        # Functions
        (cat_beg_functions, "Functions", "functions", 24,
         "Organize code into reusable, modular, named executable blocks.",
         "Functions are defined with the def keyword followed by function name and parameters in parentheses.",
         "def func_name(param1, param2):\n    return result",
         "def greet(name, language='en'):\n    greetings = {'en': 'Hello', 'es': 'Hola', 'fr': 'Bonjour'}\n    return f'{greetings.get(language, \"Hello\")}, {name}!'\n\nprint(greet('Alice'))\nprint(greet('Carlos', 'es'))",
         "Hello, Alice!\nHola, Carlos!",
         "Functions without an explicit return statement return None by default.",
         "Calling a function before it is defined in the script.",
         "Calculating order subtotals, formatting dates, hashing passwords.",
         "def square(n):\n    return n * n\nprint('5 squared is', square(5))"),

        (cat_beg_functions, "Function Arguments", "function-arguments", 25,
         "Positional, keyword, default arguments, and variable arguments (*args, **kwargs).",
         "Python functions support positional parameters, keyword arguments, default values, arbitrary positional args (*args as a tuple), and arbitrary keyword args (**kwargs as a dict).",
         "def func(*args, **kwargs): ...",
         "def build_profile(username, *skills, **details):\n    print(f'User: {username}')\n    print('Skills:', ', '.join(skills))\n    for k, v in details.items():\n        print(f'  {k}: {v}')\n\nbuild_profile('Gowtham', 'Python', 'Django', 'Docker', city='Hyderabad', role='Architect')",
         "User: Gowtham\nSkills: Python, Django, Docker\n  city: Hyderabad\n  role: Architect",
         "Default argument values are evaluated once at function definition, not each call. Never use mutable objects (like [] or {}) as defaults.",
         "Using def append_item(x, l=[]): which leads to shared state across calls.",
         "Decorator wrappers, flexible API handlers, logging utilities.",
         "def total(*nums):\n    return sum(nums)\nprint('Sum:', total(1, 2, 3, 4, 5))"),

        (cat_beg_functions, "Return Statement", "return-statement", 26,
         "Passing results back from a function to the caller.",
         "The return statement terminates function execution and specifies the value handed back to the caller.",
         "def compute():\n    return result",
         "def divide_with_remainder(a, b):\n    if b == 0:\n        return None, 'Cannot divide by zero'\n    quotient = a // b\n    remainder = a % b\n    return quotient, remainder\n\nq, r = divide_with_remainder(17, 5)\nprint(f'17 / 5 = {q} with remainder {r}')",
         "17 / 5 = 3 with remainder 2",
         "Returning multiple comma-separated values automatically packs them into a tuple.",
         "Writing code immediately following a return statement (unreachable code).",
         "Returning computation results, database records, and HTTP responses.",
         "def add(x, y):\n    return x + y\nprint(add(10, 15))"),

        (cat_beg_functions, "Scope", "scope", 27,
         "Variable visibility and resolution via Python's LEGB rule.",
         "Scope dictates where a variable is accessible. Python resolves variables using the LEGB hierarchy: Local -> Enclosing -> Global -> Built-in.",
         "global x\nnonlocal y",
         "global_var = 'I am Global'\n\ndef outer_function():\n    enclosing_var = 'I am Enclosing'\n    def inner_function():\n        local_var = 'I am Local'\n        print(local_var)\n        print(enclosing_var)\n        print(global_var)\n    inner_function()\n\nouter_function()",
         "I am Local\nI am Enclosing\nI am Global",
         "Avoid the global keyword when possible; prefer passing arguments and returning values.",
         "UnboundLocalError: referencing a global variable before assignment within local scope.",
         "Encapsulating state in closures, middleware, and decorators.",
         "counter = 0\ndef increment():\n    global counter\n    counter += 1\nincrement()\nprint('Counter:', counter)"),

        (cat_beg_functions, "Lambda Functions", "lambda-functions", 28,
         "Small, anonymous, single-expression inline functions.",
         "Lambdas are defined using the lambda keyword. They are restricted to a single expression and automatically return its result.",
         "lambda arg1, arg2: expression",
         "multiply = lambda x, y: x * y\nprint('Multiply 4 * 6:', multiply(4, 6))\n\nstudents = [('Alice', 85), ('Bob', 92), ('Charlie', 78)]\nstudents.sort(key=lambda s: s[1], reverse=True)\nprint('Sorted by score:', students)",
         "Multiply 4 * 6: 24\nSorted by score: [('Bob', 92), ('Alice', 85), ('Charlie', 78)]",
         "If the logic spans multiple statements or needs docstrings, use def instead.",
         "Assigning lambdas to names instead of using def (violates PEP 8).",
         "Custom sort keys, GUI callbacks, filter() and map() helpers.",
         "square = lambda x: x ** 2\nprint(square(9))"),
    ]

    for cat, title, slug, order, summary, content, syntax, code_ex, exp_out, notes, mistakes, real_ex, prac in beginner_topics:
        Tutorial.objects.update_or_create(
            slug=slug,
            defaults={
                'category': cat,
                'title': title,
                'order': order,
                'summary': summary,
                'content': content,
                'syntax': syntax,
                'code_example': code_ex,
                'expected_output': exp_out,
                'important_notes': notes,
                'common_mistakes': mistakes,
                'real_world_example': real_ex,
                'practice_code': prac,
                'estimated_read_time': 5,
                'is_published': True
            }
        )

    # ==========================================
    # 2. INTERMEDIATE LEVEL CATEGORIES & TOPICS
    # ==========================================
    cat_int_comp, _ = TutorialCategory.objects.get_or_create(
        slug='comprehensions-and-modules',
        defaults={'name': 'Comprehensions & Modules', 'level': 'intermediate', 'order': 7, 'icon': 'fa-cubes', 'description': 'Idiomatic Python comprehensions, modular design, and packaging.'}
    )
    cat_int_io, _ = TutorialCategory.objects.get_or_create(
        slug='io-and-exceptions',
        defaults={'name': 'Exceptions, Files & I/O', 'level': 'intermediate', 'order': 8, 'icon': 'fa-shield-halved', 'description': 'Robust error handling, file reading/writing, and JSON serialization.'}
    )
    cat_int_oop, _ = TutorialCategory.objects.get_or_create(
        slug='object-oriented-programming',
        defaults={'name': 'Object-Oriented Programming', 'level': 'intermediate', 'order': 9, 'icon': 'fa-sitemap', 'description': 'Classes, objects, inheritance, encapsulation, and polymorphism.'}
    )
    cat_int_adv_tools, _ = TutorialCategory.objects.get_or_create(
        slug='iterators-generators-decorators',
        defaults={'name': 'Iterators, Generators & Decorators', 'level': 'intermediate', 'order': 10, 'icon': 'fa-wand-magic-sparkles', 'description': 'Memory-efficient generators, iterators, and metaprogramming decorators.'}
    )
    cat_int_env, _ = TutorialCategory.objects.get_or_create(
        slug='environments-and-apis',
        defaults={'name': 'Environments, Pip & APIs', 'level': 'intermediate', 'order': 11, 'icon': 'fa-network-wired', 'description': 'Virtual environments, pip package management, and consuming REST APIs.'}
    )

    intermediate_topics = [
        (cat_int_comp, "List Comprehension", "list-comprehension", 1,
         "Concise, idiomatic syntax for creating new lists from existing iterables.",
         "List comprehensions offer a cleaner, more readable, and faster alternative to traditional for loops when mapping and filtering collections.",
         "[expression for item in iterable if condition]",
         "numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]\nsquares_of_evens = [n ** 2 for n in numbers if n % 2 == 0]\nprint('Squares of evens:', squares_of_evens)\nwords = ['python', 'django', 'code']\nupper_words = [w.upper() for w in words]\nprint('Upper words:', upper_words)",
         "Squares of evens: [4, 16, 36, 64, 100]\nUpper words: ['PYTHON', 'DJANGO', 'CODE']",
         "Keep comprehensions simple; if it requires multiple lines or complex nesting, use a regular loop.",
         "Overusing nested list comprehensions, creating unreadable one-liners.",
         "Data transformation pipelines in data analytics and API responses.",
         "nums = [1, 2, 3]\nprint([x * 10 for x in nums])"),

        (cat_int_comp, "Dictionary Comprehension", "dictionary-comprehension", 2,
         "Create dictionaries concisely from key-value pairs or iterables.",
         "Similar to list comprehensions, dictionary comprehensions provide an elegant syntax to transform or filter dictionaries.",
         "{key_expr: value_expr for item in iterable if condition}",
         "users = [('Alice', 28), ('Bob', 35), ('Charlie', 22)]\nage_map = {name: age for name, age in users if age >= 25}\nprint('Users 25+:', age_map)\n\nscores = {'math': 90, 'science': 75, 'english': 88}\ngrades = {k: ('A' if v >= 85 else 'B') for k, v in scores.items()}\nprint('Letter grades:', grades)",
         "Users 25+: {'Alice': 28, 'Bob': 35}\nLetter grades: {'math': 'A', 'science': 'B', 'english': 'A'}",
         "Both keys and values can be dynamically computed expressions.",
         "Accidentally creating duplicate keys, which silently overwrites values.",
         "Inverting key-value dictionaries for bidirectional lookup tables.",
         "names = ['apple', 'banana']\nlengths = {w: len(w) for w in names}\nprint(lengths)"),

        (cat_int_comp, "Modules", "modules", 3,
         "Organize Python code across separate files and reusable namespaces.",
         "A module is simply a Python file (.py). Python's import statement loads and caches modules in sys.modules.",
         "import math\nfrom math import sqrt",
         "import math\nprint('Pi:', round(math.pi, 4))\nprint('Square root of 144:', math.sqrt(144))\nprint('Floor of 7.8:', math.floor(7.8))",
         "Pi: 3.1416\nSquare root of 144: 12.0\nFloor of 7.8: 7",
         "Use if __name__ == '__main__': to prevent execution when imported as a module.",
         "Using wildcard imports (from math import *), which pollute the namespace.",
         "Splitting enterprise business logic into modular domain services.",
         "import random\nprint('Random choice:', random.choice(['red', 'green', 'blue']))"),

        (cat_int_comp, "Packages", "packages", 4,
         "Hierarchical module namespaces structured using directories.",
         "A package is a directory containing Python modules. Historically marked with __init__.py, packages enable structured multi-tier architectures.",
         "from my_package.submodule import my_function",
         "# Simulated package structure representation\npackage_structure = '''\nmypackage/\n├── __init__.py\n├── database.py\n└── utils/\n    ├── __init__.py\n    └── helpers.py\n'''\nprint(package_structure)",
         "\nmypackage/\n├── __init__.py\n├── database.py\n└── utils/\n    ├── __init__.py\n    └── helpers.py\n",
         "Packages allow clean namespacing and avoid naming collisions across large projects.",
         "Circular imports between modules in the same package.",
         "Organizing Django apps (views, models, forms, urls).",
         "import json\nprint('JSON package loaded:', json.__name__)"),

        (cat_int_io, "Exception Handling", "exception-handling", 5,
         "Gracefully catch and recover from runtime errors using try, except, else, and finally.",
         "Exceptions disrupt normal execution when errors occur. Handled with try/except blocks to maintain robust application uptime.",
         "try:\n    risky_operation()\nexcept Exception as e:\n    handle_error(e)\nfinally:\n    cleanup()",
         "def safe_divide(a, b):\n    try:\n        result = a / b\n    except ZeroDivisionError:\n        return 'Error: Cannot divide by zero!'\n    except TypeError as e:\n        return f'Type error: {e}'\n    else:\n        return f'Result: {result}'\n    finally:\n        pass\n\nprint(safe_divide(10, 2))\nprint(safe_divide(10, 0))",
         "Result: 5.0\nError: Cannot divide by zero!",
         "Always catch specific exceptions rather than a bare except:.",
         "Swallowing exceptions without logging or handling them silently.",
         "Handling network drops during third-party payment gateway calls.",
         "try:\n    val = int('not_a_number')\nexcept ValueError:\n    print('Handled ValueError')"),

        (cat_int_io, "File Handling", "file-handling", 6,
         "Read, write, and manage files safely using context managers.",
         "Use Python's built-in open() with the with statement (context manager) to ensure files are closed automatically even if exceptions occur.",
         "with open('file.txt', 'r', encoding='utf-8') as f:\n    data = f.read()",
         "# Demonstrating in-memory file I/O safely\nimport io\nstream = io.StringIO()\nstream.write('Line 1: System initialized\\nLine 2: Server running')\nstream.seek(0)\n\nfor line in stream:\n    print('Read:', line.strip())",
         "Read: Line 1: System initialized\nRead: Line 2: Server running",
         "Always specify encoding='utf-8' when opening text files across platforms.",
         "Forgetting to close files when not using the with statement.",
         "Generating automated PDF reports or saving incoming user uploads.",
         "import io\nbuf = io.StringIO('Hello file!')\nprint(buf.read())"),

        (cat_int_io, "JSON", "json-processing", 7,
         "Parse, manipulate, and serialize JavaScript Object Notation in Python.",
         "Python's json standard library module provides dumps()/dump() for serialization and loads()/load() for deserialization.",
         "import json\ndata = json.loads(json_str)\njson_str = json.dumps(data, indent=2)",
         "import json\nuser_data = {'id': 101, 'name': 'Gowtham', 'skills': ['Python', 'Django'], 'active': True}\njson_str = json.dumps(user_data, indent=2)\nprint('Serialized JSON:\\n' + json_str)\nparsed = json.loads(json_str)\nprint('Parsed back user name:', parsed['name'])",
         "Serialized JSON:\n{\n  \"id\": 101,\n  \"name\": \"Gowtham\",\n  \"skills\": [\n    \"Python\",\n    \"Django\"\n  ],\n  \"active\": true\n}\nParsed back user name: Gowtham",
         "Python None serializes to JSON null; True/False serialize to true/false.",
         "Attempting to serialize datetime or custom class instances directly without custom JSONEncoder.",
         "Building REST API responses and exchanging web payloads.",
         "import json\nprint(json.loads('{\"status\": \"ok\"}')['status'])"),

        (cat_int_io, "Date and Time", "date-and-time", 8,
         "Work with dates, timestamps, durations, and timezones using datetime.",
         "The datetime module provides date, time, datetime, and timedelta classes. Use strftime() for formatting and strptime() for parsing.",
         "from datetime import datetime, timedelta\nnow = datetime.now()",
         "from datetime import date, timedelta\ntoday = date(2026, 10, 6)\nweek_later = today + timedelta(days=7)\nprint('Current date:', today.strftime('%B %d, %Y'))\nprint('One week later:', week_later.strftime('%B %d, %Y'))\nprint('Days between:', (week_later - today).days)",
         "Current date: October 06, 2026\nOne week later: October 13, 2026\nDays between: 7",
         "Always store and compute dates in UTC time in databases and APIs.",
         "Mixing timezone-naive and timezone-aware datetimes causes TypeError.",
         "Calculating subscription expiry dates and invoice billing schedules.",
         "from datetime import date\nprint('Today:', date.today())"),

        (cat_int_io, "Regular Expressions", "regular-expressions", 9,
         "Pattern matching and text extraction using the re module.",
         "Regular expressions provide powerful pattern matching tools. Use raw strings (r'...') to avoid backslash escaping conflicts.",
         "import re\nmatch = re.search(pattern, text)\nmatches = re.findall(pattern, text)",
         "import re\ntext = 'Contact support@pymaster.dev or admin@example.com for help.'\nemails = re.findall(r'[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}', text)\nprint('Found emails:', emails)\ncleaned = re.sub(r'\\s+', ' ', 'Multiple    spaces   compacted')\nprint('Cleaned text:', cleaned)",
         "Found emails: ['support@pymaster.dev', 'admin@example.com']\nCleaned text: Multiple spaces compacted",
         "Compile regexes with re.compile() if they are evaluated repeatedly in a loop.",
         "Overusing complex regexes when simple string methods (.startswith, .replace) suffice.",
         "Validating user input (phone numbers, postal codes, email addresses).",
         "import re\nprint(re.findall(r'\\d+', 'Order 452 had 3 items'))"),

        # OOP
        (cat_int_oop, "Object-Oriented Programming", "object-oriented-programming", 10,
         "Introduction to OOP principles: encapsulation, abstraction, inheritance, polymorphism.",
         "OOP bundles data (attributes) and behavior (methods) into reusable objects, mirroring real-world entities.",
         "class Entity:\n    def __init__(self, name):\n        self.name = name",
         "class Account:\n    def __init__(self, owner, balance=0):\n        self.owner = owner\n        self.balance = balance\n    def deposit(self, amount):\n        self.balance += amount\n        return self.balance\n\nacc = Account('Gowtham', 500)\nacc.deposit(250)\nprint(f'{acc.owner}\\'s balance: ${acc.balance}')",
         "Gowtham's balance: $750",
         "In Python, self represents the instance of the class and must be explicitly declared as the first parameter in methods.",
         "Forgetting self in method declarations or calls.",
         "Modeling financial accounts, game characters, and database entities.",
         "class Dog:\n    def speak(self): return 'Woof!'\nprint(Dog().speak())"),

        (cat_int_oop, "Classes", "classes", 11,
         "Define blueprints for creating user-defined objects and types.",
         "A class bundles state and logic. Class attributes belong to the class, while instance attributes belong to specific objects.",
         "class ClassName:\n    class_attr = 'shared'\n    def method(self): ...",
         "class Book:\n    library_branch = 'Downtown'  # Class attribute\n    def __init__(self, title, author):\n        self.title = title       # Instance attribute\n        self.author = author\n\nb1 = Book('1984', 'George Orwell')\nprint(f'Book: {b1.title} at {Book.library_branch}')",
         "Book: 1984 at Downtown",
         "Class attributes are shared across all instances; changing them on an instance creates an instance-level override.",
         "Accidentally mutating a shared mutable class attribute.",
         "Designing data models in Django, SQLAlchemy, or Pydantic.",
         "class Car:\n    pass\nprint(type(Car()))"),

        (cat_int_oop, "Objects", "objects", 12,
         "Instantiate, inspect, and interact with class instances.",
         "An object is an instance of a class. Built-in functions like isinstance() and hasattr() provide dynamic inspection.",
         "obj = MyClass()\nisinstance(obj, MyClass)",
         "class Laptop:\n    def __init__(self, brand, ram_gb):\n        self.brand = brand\n        self.ram_gb = ram_gb\n\nl1 = Laptop('Dell', 16)\nprint('Instance brand:', l1.brand)\nprint('Is Laptop instance?', isinstance(l1, Laptop))\nprint('Has ram_gb attribute?', hasattr(l1, 'ram_gb'))",
         "Instance brand: Dell\nIs Laptop instance? True\nHas ram_gb attribute? True",
         "Objects are passed by object reference in Python.",
         "Confusing class methods with instance methods.",
         "Managing active connection pools, UI widgets, and game entities.",
         "class Player:\n    name = 'Hero'\np = Player()\nprint(p.name)"),

        (cat_int_oop, "Constructors", "constructors", 13,
         "Initialize object state using the __init__ dunder constructor.",
         "__init__ is the initializer method called automatically right after an object is instantiated to set up initial state.",
         "def __init__(self, *args, **kwargs):\n    self.attr = val",
         "class Employee:\n    def __init__(self, name, department, salary=50000):\n        self.name = name\n        self.department = department\n        self.salary = salary\n    def __str__(self):\n        return f'{self.name} ({self.department}) - ${self.salary}'\n\ne = Employee('Alice', 'Engineering', 85000)\nprint(e)",
         "Alice (Engineering) - $85000",
         "__init__ must never return a value; doing so raises TypeError.",
         "Attempting to return a value from __init__.",
         "Configuring database connection clients with host, port, and credentials.",
         "class User:\n    def __init__(self, u):\n        self.username = u\nprint(User('dev').username)"),

        (cat_int_oop, "Inheritance", "inheritance", 14,
         "Derive child classes from parent classes to reuse and extend functionality.",
         "Inheritance allows a subclass to inherit attributes and methods from a superclass. Use super() to call parent methods.",
         "class Child(Parent):\n    def __init__(self): super().__init__()",
         "class Animal:\n    def __init__(self, name):\n        self.name = name\n    def speak(self):\n        return 'Some sound'\n\nclass Dog(Animal):\n    def speak(self):\n        return f'{self.name} says Woof!'\n\nd = Dog('Buddy')\nprint(d.speak())",
         "Buddy says Woof!",
         "Python supports multiple inheritance; method resolution order (MRO) can be inspected via ClassName.mro().",
         "Not calling super().__init__() when overriding __init__ in a subclass.",
         "Creating specialized user roles (Admin, Moderator, Customer) from a base User.",
         "class Vehicle: pass\nclass Car(Vehicle): pass\nprint(issubclass(Car, Vehicle))"),

        (cat_int_oop, "Polymorphism", "polymorphism", 15,
         "Uniform interfaces across different classes and Python duck typing.",
         "Polymorphism allows different classes to implement the same interface. In Python, 'if it walks like a duck and quacks like a duck, it is a duck'.",
         "for item in items:\n    item.action()",
         "class Circle:\n    def draw(self): return 'Drawing Circle ⭕'\n\nclass Square:\n    def draw(self): return 'Drawing Square ⏹️'\n\nshapes = [Circle(), Square(), Circle()]\nfor s in shapes:\n    print(s.draw())",
         "Drawing Circle ⭕\nDrawing Square ⏹️\nDrawing Circle ⭕",
         "Python does not require interfaces or abstract base classes for polymorphism thanks to duck typing.",
         "Excessively type-checking with type() rather than checking capabilities or using isinstance().",
         "Handling multiple payment processors (Stripe, PayPal) through a common .charge() method.",
         "class Audio: play = lambda s: 'Playing audio'\nclass Video: play = lambda s: 'Playing video'\nprint([x.play() for x in [Audio(), Video()]])"),

        (cat_int_oop, "Encapsulation", "encapsulation", 16,
         "Protect internal state using private attributes and @property decorators.",
         "In Python, private attributes are designated with a leading underscore (_internal) or double underscore (__private, which triggers name mangling). Properties provide clean getter/setter access.",
         "@property\ndef balance(self):\n    return self._balance",
         "class BankAccount:\n    def __init__(self, initial):\n        self._balance = initial\n    @property\n    def balance(self):\n        return self._balance\n    @balance.setter\n    def balance(self, value):\n        if value < 0:\n            raise ValueError('Balance cannot be negative')\n        self._balance = value\n\nb = BankAccount(100)\nb.balance = 250\nprint('Validated balance:', b.balance)",
         "Validated balance: 250",
         "In Python, privacy is by convention ('we are all consenting adults here').",
         "Writing explicit get_x() and set_x() methods instead of using the @property decorator.",
         "Validating user age or sanitizing email addresses during assignment.",
         "class Box:\n    def __init__(self, w): self.w = w\nprint(Box(10).w)"),

        # Advanced tools
        (cat_int_adv_tools, "Iterators", "iterators", 17,
         "The iterator protocol: __iter__() and __next__() methods.",
         "An iterator is an object that implements the iterator protocol. You fetch values using next(), which raises StopIteration when exhausted.",
         "iterator = iter(iterable)\nvalue = next(iterator)",
         "numbers = [10, 20, 30]\nit = iter(numbers)\nprint(next(it))\nprint(next(it))\nprint(next(it))\n# Next call would raise StopIteration",
         "10\n20\n30",
         "All iterators are iterables, but not all iterables are iterators.",
         "Re-iterating over an exhausted iterator without re-creating it.",
         "Streaming database cursors row-by-row without loading entire tables into memory.",
         "it = iter(['a', 'b'])\nprint('First:', next(it))"),

        (cat_int_adv_tools, "Generators", "generators", 18,
         "Lazy evaluation and memory efficiency with the yield keyword.",
         "Generators are functions that yield values on demand. They preserve local state between iterations, providing tremendous memory savings for large sequences.",
         "def gen():\n    yield val",
         "def countdown_gen(n):\n    while n > 0:\n        yield n\n        n -= 1\n\nfor val in countdown_gen(3):\n    print('Countdown:', val)",
         "Countdown: 3\nCountdown: 2\nCountdown: 1",
         "Generators produce values lazily on demand; they take O(1) memory regardless of sequence size.",
         "Trying to index into a generator (e.g. gen[0] raises TypeError).",
         "Reading massive 50GB log files line-by-line without crashing server RAM.",
         "def evens():\n    for i in range(10):\n        if i % 2 == 0: yield i\nprint(list(evens()))"),

        (cat_int_adv_tools, "Decorators", "decorators", 19,
         "Wrap and augment functions dynamically using @decorator syntax.",
         "Decorators are functions that take another function as an argument, extend its behavior without modifying the original code, and return a callable.",
         "@my_decorator\ndef func(): ...",
         "def audit_log(func):\n    def wrapper(*args, **kwargs):\n        print(f'[AUDIT] Executing {func.__name__}...')\n        result = func(*args, **kwargs)\n        print(f'[AUDIT] Finished {func.__name__}')\n        return result\n    return wrapper\n\n@audit_log\ndef calculate_tax(amount):\n    return amount * 0.15\n\nprint('Tax:', calculate_tax(100))",
         "[AUDIT] Executing calculate_tax...\n[AUDIT] Finished calculate_tax\nTax: 15.0",
         "Use functools.wraps to preserve the original function's name and docstring.",
         "Forgetting to accept *args, **kwargs in the inner wrapper function.",
         "Authentication checks, rate limiting, and performance profiling in web frameworks.",
         "def shout(f):\n    return lambda: f().upper()\n@shout\ndef hi(): return 'hi'\nprint(hi())"),

        # Environments and APIs
        (cat_int_env, "Virtual Environment", "virtual-environment", 20,
         "Isolate project dependencies using venv to prevent version collisions.",
         "Virtual environments ensure each Python project has its own isolated set of installed packages and interpreter binaries.",
         "python -m venv venv\nsource venv/bin/activate  # Mac/Linux\n.\\venv\\Scripts\\activate  # Windows",
         "import sys\nprint('Current Python Executable:', sys.executable)\nprint('In virtual environment?', hasattr(sys, 'real_prefix') or (hasattr(sys, 'base_prefix') and sys.base_prefix != sys.prefix))",
         "Current Python Executable: ...\nIn virtual environment? True",
         "Never commit your virtual environment folder (venv/) to Git; commit requirements.txt instead.",
         "Installing packages globally without an active virtual environment.",
         "Running multiple projects requiring different conflicting Django or library versions.",
         "import sys\nprint('Prefix:', sys.prefix)"),

        (cat_int_env, "pip", "pip-package-manager", 21,
         "Install, upgrade, manage, and freeze Python packages from PyPI.",
         "pip is Python's standard package installer. It fetches libraries from the Python Package Index (PyPI).",
         "pip install package_name\npip freeze > requirements.txt",
         "# Common pip workflow reference\nprint('pip install django')\nprint('pip freeze > requirements.txt')\nprint('pip install -r requirements.txt')",
         "pip install django\npip freeze > requirements.txt\npip install -r requirements.txt",
         "Pin exact dependency versions in production using == (e.g. Django==5.1.0).",
         "Not pinning versions, leading to broken builds when upstream libraries update.",
         "Deploying containerized microservices with reproducible dependency trees.",
         "print('pip version management verified')"),

        (cat_int_env, "APIs", "apis", 22,
         "Understand REST architectural principles, HTTP methods, and status codes.",
         "Application Programming Interfaces allow applications to communicate. REST APIs use HTTP methods (GET, POST, PUT, DELETE) and standard status codes (200, 201, 400, 404, 500).",
         "# GET: Retrieve resource\n# POST: Create resource\n# PUT: Update resource\n# DELETE: Remove resource",
         "status_codes = {\n    200: 'OK - Success',\n    201: 'Created - Resource created',\n    400: 'Bad Request - Client error',\n    401: 'Unauthorized',\n    404: 'Not Found',\n    500: 'Internal Server Error'\n}\nfor code, desc in status_codes.items():\n    print(f'{code}: {desc}')",
         "200: OK - Success\n201: Created - Resource created\n400: Bad Request - Client error\n401: Unauthorized\n404: Not Found\n500: Internal Server Error",
         "REST APIs are stateless; each request must contain all necessary authentication and parameters.",
         "Using GET requests for operations that modify server state.",
         "Communicating between single-page frontend apps and backend servers.",
         "print('API Architecture: Client -> HTTP Request -> REST Endpoint -> Response')"),

        (cat_int_env, "Working with JSON APIs", "working-with-json-apis", 23,
         "Consume web services and process remote JSON responses.",
         "Python standard library (urllib) and third-party libraries (requests, httpx) make making HTTP calls and deserializing JSON straightforward.",
         "import json, urllib.request\nwith urllib.request.urlopen(url) as response:\n    data = json.loads(response.read())",
         "import json\n# Simulating API response processing\nmock_response = '{\"status\": \"success\", \"data\": [{\"id\": 1, \"name\": \"Python Book\", \"price\": 29.99}]}'\npayload = json.loads(mock_response)\nprint('API Status:', payload['status'])\nfor item in payload['data']:\n    print(f'Item: {item[\"name\"]} - ${item[\"price\"]}')",
         "API Status: success\nItem: Python Book - $29.99",
         "Always check response status codes and handle connection timeouts gracefully.",
         "Assuming external APIs will always be online or return successful responses.",
         "Integrating weather feeds, payment gateways, and translation APIs.",
         "import json\nres = json.loads('{\"authenticated\": true}')\nprint(res['authenticated'])"),
    ]

    for cat, title, slug, order, summary, content, syntax, code_ex, exp_out, notes, mistakes, real_ex, prac in intermediate_topics:
        Tutorial.objects.update_or_create(
            slug=slug,
            defaults={
                'category': cat,
                'title': title,
                'order': order,
                'summary': summary,
                'content': content,
                'syntax': syntax,
                'code_example': code_ex,
                'expected_output': exp_out,
                'important_notes': notes,
                'common_mistakes': mistakes,
                'real_world_example': real_ex,
                'practice_code': prac,
                'estimated_read_time': 7,
                'is_published': True
            }
        )

    # ==========================================
    # 3. ADVANCED LEVEL CATEGORIES & TOPICS
    # ==========================================
    cat_adv_arch, _ = TutorialCategory.objects.get_or_create(
        slug='advanced-python-architecture',
        defaults={'name': 'Advanced Architecture & Concurrency', 'level': 'advanced', 'order': 12, 'icon': 'fa-microchip', 'description': 'Asyncio, multithreading, multiprocessing, and advanced OOP patterns.'}
    )
    cat_adv_testing, _ = TutorialCategory.objects.get_or_create(
        slug='typing-testing-quality',
        defaults={'name': 'Type Hints, Testing & Logging', 'level': 'advanced', 'order': 13, 'icon': 'fa-vial-circle-check', 'description': 'Modern Python type hints, dataclasses, pytest, and production logging.'}
    )
    cat_adv_web, _ = TutorialCategory.objects.get_or_create(
        slug='databases-django-automation',
        defaults={'name': 'Django, Databases & Automation', 'level': 'advanced', 'order': 14, 'icon': 'fa-server', 'description': 'Database access, web development with Django, REST frameworks, and data processing.'}
    )

    advanced_topics = [
        (cat_adv_arch, "Advanced OOP", "advanced-oop", 1,
         "Metaclasses, abstract base classes, descriptors, and dunder magic methods.",
         "Advanced OOP in Python delves into dynamic attribute access (__getattr__, __setattr__), custom descriptors, and the abc module for enforcing interface contracts.",
         "from abc import ABC, abstractmethod\nclass Base(ABC):\n    @abstractmethod\n    def execute(self): pass",
         "from abc import ABC, abstractmethod\n\nclass DataSink(ABC):\n    @abstractmethod\n    def save(self, record):\n        pass\n\nclass MemorySink(DataSink):\n    def __init__(self):\n        self.records = []\n    def save(self, record):\n        self.records.append(record)\n        return f'Saved {record}'\n\nsink = MemorySink()\nprint(sink.save('Audit #412'))",
         "Saved Audit #412",
         "Abstract Base Classes prevent accidental instantiation of incomplete implementations.",
         "Over-engineering simple problems with unnecessary metaclasses.",
         "Building extensible plugin architectures in developer tools.",
         "from abc import ABC; print('ABC module available')"),

        (cat_adv_arch, "Async Programming", "async-programming", 2,
         "Asynchronous event loops, coroutines, and non-blocking I/O using asyncio.",
         "asyncio uses cooperative multitasking with an event loop to handle thousands of concurrent network connections efficiently without OS thread overhead.",
         "async def fetch_data():\n    await asyncio.sleep(1)\n    return 'Done'",
         "# Demonstrating coroutine definition\nimport asyncio\n\nasync def simulate_task(name, delay):\n    return f'Task {name} complete after {delay}s'\n\n# Coroutines are first-class objects in Python\nprint('Defined async task:', simulate_task.__name__)",
         "Defined async task: simulate_task",
         "Use async for I/O-bound tasks (web scraping, database queries, APIs), not CPU-bound calculations.",
         "Calling blocking synchronous code (like time.sleep) inside async functions, which blocks the whole event loop.",
         "High-throughput WebSocket chat servers and real-time streaming backends.",
         "async def main(): return 42\nprint('Async coroutine created')"),

        (cat_adv_arch, "Multithreading", "multithreading", 3,
         "Concurrent execution for I/O-bound tasks with the threading module.",
         "Threads share memory within the same process. Due to Python's Global Interpreter Lock (GIL), multithreading is ideal for concurrent I/O operations.",
         "import threading\nt = threading.Thread(target=task)\nt.start()\nt.join()",
         "import threading\ndef worker(num):\n    print(f'Thread {num} running')\n\nthreads = []\nfor i in range(2):\n    t = threading.Thread(target=worker, args=(i,))\n    threads.append(t)\n    t.start()\nfor t in threads:\n    t.join()",
         "Thread 0 running\nThread 1 running",
         "The GIL limits pure Python bytecode execution to one thread at a time.",
         "Race conditions when multiple threads read and mutate shared variables without locks.",
         "Simultaneously downloading 50 thumbnail images from an S3 bucket.",
         "import threading\nprint('Active threads:', threading.active_count())"),

        (cat_adv_arch, "Multiprocessing", "multiprocessing", 4,
         "Bypass the GIL to utilize multiple CPU cores for heavy computational workloads.",
         "The multiprocessing module spawns separate OS processes, each with its own Python interpreter and memory space, enabling true parallel CPU computation.",
         "from multiprocessing import Pool\nwith Pool(4) as p:\n    results = p.map(func, data)",
         "import os\nprint('Current Process ID (PID):', os.getpid())\nprint('CPU Cores available:', os.cpu_count())",
         "Current Process ID (PID): ...\nCPU Cores available: ...",
         "Processes do not share memory by default; data must be serialized (pickled) between processes.",
         "Forgetting the if __name__ == '__main__': guard when spawning processes on Windows.",
         "Image processing, machine learning training, and cryptographic hash verification.",
         "import os\nprint('Process ID exists:', bool(os.getpid()))"),

        (cat_adv_testing, "Type Hints", "type-hints", 5,
         "Static typing, type annotations, and static analysis with mypy.",
         "Type hints (PEP 484) add optional type annotations to variables, function parameters, and return types, improving IDE autocompletion and static verification.",
         "def calculate_total(prices: list[float], tax_rate: float) -> float: ...",
         "def format_user(name: str, age: int, tags: list[str]) -> str:\n    return f'{name} ({age}) - Tags: {', '.join(tags)}'\n\nprint(format_user('Gowtham', 25, ['python', 'dev']))",
         "Gowtham (25) - Tags: python, dev",
         "Type hints are not enforced at runtime by default; they serve as contracts for linters and IDEs.",
         "Expecting Python to throw a runtime error if a wrong type is passed without a validator library like Pydantic.",
         "Maintaining clean contracts in large microservices and shared codebases.",
         "def add(a: int, b: int) -> int: return a + b\nprint(add(5, 7))"),

        (cat_adv_testing, "Dataclasses", "dataclasses", 6,
         "Generate boilerplate class code automatically with the @dataclass decorator.",
         "Introduced in Python 3.7, dataclasses automatically generate __init__, __repr__, __eq__, and comparison methods based on typed class attributes.",
         "from dataclasses import dataclass\n@dataclass\nclass Product:\n    name: str\n    price: float",
         "from dataclasses import dataclass, field\n\n@dataclass\nclass CourseLesson:\n    title: str\n    duration_mins: int = 10\n    completed: bool = False\n\nlesson = CourseLesson('Python Dataclasses', 15)\nprint(lesson)\nprint('Lesson title:', lesson.title)",
         "CourseLesson(title='Python Dataclasses', duration_mins=15, completed=False)\nLesson title: Python Dataclasses",
         "Use frozen=True to create immutable value objects that can be used as set members or dictionary keys.",
         "Using mutable default values (like tags: list = []) without field(default_factory=list).",
         "DTOs (Data Transfer Objects) and structured configuration containers.",
         "from dataclasses import dataclass\n@dataclass\nclass Point:\n    x: int; y: int\nprint(Point(1, 2))"),

        (cat_adv_testing, "Testing", "testing-basics", 7,
         "Automated unit testing with Python's built-in unittest module.",
         "Automated tests verify that your code works as expected and prevents regressions when refactoring.",
         "import unittest\nclass TestApp(unittest.TestCase):\n    def test_logic(self):\n        self.assertEqual(a, b)",
         "import unittest\n\ndef add(x, y): return x + y\n\nclass TestMath(unittest.TestCase):\n    def test_add(self):\n        self.assertEqual(add(2, 3), 5)\n        self.assertEqual(add(-1, 1), 0)\n\nsuite = unittest.TestLoader().loadTestsFromTestCase(TestMath)\nrunner = unittest.TextTestRunner(verbosity=0)\nresult = runner.run(suite)\nprint('Tests run:', result.testsRun, '| Errors/Failures:', len(result.errors) + len(result.failures))",
         "Tests run: 1 | Errors/Failures: 0",
         "Follow the AAA pattern in tests: Arrange, Act, Assert.",
         "Writing tests that depend on external live databases or third-party APIs without mocking.",
         "CI/CD deployment validation pipelines on GitHub Actions or GitLab CI.",
         "import unittest\nprint('unittest ready')"),

        (cat_adv_testing, "Pytest", "pytest-framework", 8,
         "Modern, expressive, and concise testing with pytest fixtures and parameterization.",
         "pytest is the most popular testing framework in the Python ecosystem. It replaces verbose assertions with plain assert statements and provides powerful fixtures.",
         "# test_sample.py\ndef test_feature():\n    assert calculate(2) == 4",
         "# Demonstration of pytest assertions syntax\ndef check_discount(price, pct):\n    return price * (1 - pct)\n\n# Plain assert in pytest:\nassert check_discount(100, 0.2) == 80.0\nprint('Assertion passed: 20% discount on $100 is $80.0')",
         "Assertion passed: 20% discount on $100 is $80.0",
         "pytest fixtures handle reusable setup and teardown cleanly across test suites.",
         "Writing monolithic test functions instead of small, single-assertion tests.",
         "End-to-end integration and API regression test suites.",
         "assert 1 + 1 == 2\nprint('pytest assert style works!')"),

        (cat_adv_testing, "Logging", "logging", 9,
         "Track runtime events and debug production applications with the logging module.",
         "Never use print() for debugging in production code. The logging module provides hierarchical loggers, levels (DEBUG, INFO, WARNING, ERROR, CRITICAL), and flexible output destinations.",
         "import logging\nlogging.basicConfig(level=logging.INFO)\nlogging.info('Message')",
         "import logging\nimport io\n\nlog_stream = io.StringIO()\nhandler = logging.StreamHandler(log_stream)\nhandler.setFormatter(logging.Formatter('[%(levelname)s] %(message)s'))\n\nlogger = logging.getLogger('demo')\nlogger.setLevel(logging.INFO)\nlogger.addHandler(handler)\n\nlogger.info('System startup initiated')\nlogger.warning('High memory usage detected')\nprint(log_stream.getvalue().strip())",
         "[INFO] System startup initiated\n[WARNING] High memory usage detected",
         "Log structured messages or key-value pairs to facilitate ingestion by Datadog, ELK, or CloudWatch.",
         "Hardcoding logging output without allowing level configuration via environment variables.",
         "Capturing stack traces of unhandled exceptions in production servers.",
         "import logging\nprint('Logging module imported')"),

        (cat_adv_testing, "Python Project Structure", "project-structure", 10,
         "Professional folder layouts, pyproject.toml, src layout, and packaging best practices.",
         "Modern Python projects use a standard layout containing tests/, src/, docs/, pyproject.toml, and README.md.",
         "my_project/\n├── pyproject.toml\n├── src/my_pkg/\n└── tests/",
         "structure = '''\nmy_project/\n├── pyproject.toml\n├── README.md\n├── src/\n│   └── my_app/\n│       ├── __init__.py\n│       └── core.py\n└── tests/\n    └── test_core.py\n'''\nprint(structure)",
         "\nmy_project/\n├── pyproject.toml\n├── README.md\n├── src/\n│   └── my_app/\n│       ├── __init__.py\n│       └── core.py\n└── tests/\n    └── test_core.py\n",
         "Using a src/ layout avoids accidental imports of development code over installed package versions.",
         "Putting all code files flat in the root directory of a growing project.",
         "Structuring open-source libraries published to PyPI.",
         "print('Standard project structure verified')"),

        (cat_adv_web, "Database Programming", "database-programming", 11,
         "Relational databases, SQL queries, and ORM integration.",
         "Python connects to SQL databases (SQLite, PostgreSQL, MySQL) via DB-API 2.0 drivers or high-level Object-Relational Mappers (ORMs).",
         "import sqlite3\nconn = sqlite3.connect('db.sqlite3')",
         "import sqlite3\nconn = sqlite3.connect(':memory:')\ncur = conn.cursor()\ncur.execute('CREATE TABLE users (id INTEGER PRIMARY KEY, name TEXT)')\ncur.execute('INSERT INTO users (name) VALUES (?)', ('Gowtham',))\nconn.commit()\n\ncur.execute('SELECT * FROM users')\nprint('Query result:', cur.fetchall())\nconn.close()",
         "Query result: [(1, 'Gowtham')]",
         "Always use parameterized queries (with ? or %s) to prevent SQL injection vulnerabilities.",
         "String-formatting or concatenating raw user inputs into SQL strings.",
         "Persisting user accounts, transactional orders, and inventory state.",
         "import sqlite3\nprint('SQLite3 in-memory supported')"),

        (cat_adv_web, "Web Development with Django", "web-development-django", 12,
         "Build robust web applications with the 'batteries-included' Django framework.",
         "Django follows the Model-View-Template (MVT) pattern. It includes an ORM, authentication, admin panel, URL dispatcher, and robust security by default.",
         "# Django MVT Architecture\n# URL -> View -> Model/Database -> Template",
         "from django.conf import settings\nprint('Django Framework is active!')\nprint('Configured Apps count:', len(settings.INSTALLED_APPS))",
         "Django Framework is active!\nConfigured Apps count: ...",
         "Django handles CSRF, SQL injection, and clickjacking protection out of the box.",
         "Running business logic directly inside HTML templates instead of views or model methods.",
         "Building full-stack platforms, SaaS applications, and e-commerce stores.",
         "import django\nprint('Django version:', django.get_version())"),

        (cat_adv_web, "REST APIs", "rest-apis-django", 13,
         "Build modern RESTful Web APIs using Django REST Framework (DRF).",
         "DRF provides powerful serializers, viewsets, authentication schemes, and browsable API explorers for building scalable backend endpoints.",
         "from rest_framework import serializers, viewsets\nclass UserSerializer(serializers.ModelSerializer): ...",
         "from rest_framework import serializers\n\nclass SampleSerializer(serializers.Serializer):\n    title = serializers.CharField(max_length=100)\n    score = serializers.IntegerField()\n\ns = SampleSerializer(data={'title': 'PyMaster API', 'score': 99})\nprint('Is valid?', s.is_valid())\nprint('Validated data:', s.validated_data)",
         "Is valid? True\nValidated data: {'title': 'PyMaster API', 'score': 99}",
         "DRF serializers validate incoming JSON payloads and convert complex model instances into native Python types.",
         "Neglecting to paginate large queryset responses, leading to slow network responses.",
         "Serving data to React, Vue, mobile apps, and third-party integrations.",
         "import rest_framework\nprint('DRF Version:', rest_framework.__version__)"),

        (cat_adv_web, "Python Automation", "python-automation", 14,
         "Automate repetitive daily workflows, file batching, and web tasks.",
         "Python is the undisputed king of scripting and automation. You can automate email dispatches, file renaming, data scraping, and system backups.",
         "import os, pathlib\nfor f in pathlib.Path('.').glob('*.csv'):\n    process(f)",
         "import pathlib\n# Simulating file batch organization\nfilenames = ['invoice_001.pdf', 'photo_002.jpg', 'invoice_003.pdf']\npdf_files = [f for f in filenames if f.endswith('.pdf')]\nprint('Automated PDF filter found:', pdf_files)",
         "Automated PDF filter found: ['invoice_001.pdf', 'invoice_003.pdf']",
         "Use the pathlib module rather than raw os.path string manipulations for cross-platform file paths.",
         "Hardcoding OS-specific file paths (like C:\\) that fail on Linux servers.",
         "Automatically renaming thousands of photo files or archiving weekly reports.",
         "import pathlib\nprint('Pathlib current path:', pathlib.Path('.').resolve().name)"),

        (cat_adv_web, "Data Processing", "data-processing", 15,
         "Transform, clean, aggregate, and analyze tabular data with Python.",
         "Python provides built-in modules (csv, collections, itertools) and scientific packages for processing, transforming, and summarizing large datasets.",
         "from collections import Counter\ncounts = Counter(data)",
         "from collections import Counter\nwords = ['python', 'code', 'data', 'python', 'code', 'python', 'ai']\ncounts = Counter(words)\nprint('Top word counts:', counts.most_common(2))\nprint('Total words processed:', sum(counts.values()))",
         "Top word counts: [('python', 3), ('code', 2)]\nTotal words processed: 7",
         "Built-in collections.defaultdict and Counter are often much faster than manual dict loops.",
         "Loading entire gigabyte files into memory when a streaming generator would suffice.",
         "Aggregating website visit analytics and calculating daily revenue metrics.",
         "from collections import Counter\nprint(Counter([1, 1, 2]))"),
    ]

    for cat, title, slug, order, summary, content, syntax, code_ex, exp_out, notes, mistakes, real_ex, prac in advanced_topics:
        Tutorial.objects.update_or_create(
            slug=slug,
            defaults={
                'category': cat,
                'title': title,
                'order': order,
                'summary': summary,
                'content': content,
                'syntax': syntax,
                'code_example': code_ex,
                'expected_output': exp_out,
                'important_notes': notes,
                'common_mistakes': mistakes,
                'real_world_example': real_ex,
                'practice_code': prac,
                'estimated_read_time': 8,
                'is_published': True
            }
        )

    print("Tutorials seeded successfully.")
