# Generated by Django 6.1.1 on 2026-10-06 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('description', models.TextField()),
                ('requirements', models.TextField(help_text='List of requirements/prerequisites (one per line or markdown)')),
                ('concepts_used', models.CharField(help_text='Comma separated concepts, e.g. OOP, File I/O, Requests', max_length=300)),
                ('step_by_step_guide', models.TextField(help_text='Detailed implementation tutorial in Markdown')),
                ('source_code', models.TextField(help_text='Complete production-grade runnable source code')),
                ('challenges', models.TextField(blank=True, default='', help_text='Take-it-further exercises and challenges')),
                ('order', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['level', 'order', 'title'],
            },
        ),
    ]
