# Generated by Django 6.1.1 on 2026-10-06 05:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('icon', models.CharField(default='fa-laptop-code', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name_plural': 'Exercise Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=10)),
                ('description', models.TextField(help_text='Detailed problem statement in Markdown')),
                ('example_input', models.TextField(blank=True, default='')),
                ('example_output', models.TextField(blank=True, default='')),
                ('starter_code', models.TextField(help_text='Template code provided to learner')),
                ('solution_code', models.TextField(help_text='Reference solution code')),
                ('explanation', models.TextField(blank=True, default='', help_text='Explanation revealed after solving')),
                ('hints', models.TextField(blank=True, default='', help_text='Helpful hints for solving')),
                ('points', models.PositiveIntegerField(default=10)),
                ('order', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='exercises.exercisecategory')),
            ],
            options={
                'ordering': ['difficulty', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_code', models.TextField()),
                ('passed', models.BooleanField(default=False)),
                ('score', models.PositiveIntegerField(default=0)),
                ('test_cases_passed', models.PositiveIntegerField(default=0)),
                ('total_test_cases', models.PositiveIntegerField(default=0)),
                ('execution_time', models.FloatField(default=0.0)),
                ('output_log', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='exercises.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField(blank=True, default='', help_text='Stdin input or argument')),
                ('expected_output', models.TextField(help_text='Exact expected stdout output')),
                ('is_sample', models.BooleanField(default=True, help_text='Whether this test case is visible in problem description')),
                ('order', models.PositiveIntegerField(default=1)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='exercises.exercise')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
