# Generated by Django 6.1.1 on 2026-10-06 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_dynamic',
            field=models.BooleanField(default=False, help_text='Generated dynamically via Quiz Generator'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='total_questions_count',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='is_skipped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='marks_earned',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='user_answer_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='category',
            field=models.CharField(default='Python Basics', max_length=100),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=10),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='question_data',
            field=models.JSONField(blank=True, default=dict, help_text='JSON structured data for matching pairs, code blocks, test cases, etc.'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('mixed', 'Mixed Levels')], default='beginner', max_length=20),
        ),
        migrations.AlterField(
            model_name='quizanswer',
            name='text_answer',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='total_marks',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='quizoption',
            name='option_text',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='code_snippet',
            field=models.TextField(blank=True, default='', help_text='Optional Python code snippet or starter code'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='fill_blank_answer',
            field=models.CharField(blank=True, default='', help_text='Accepted answer for text questions', max_length=255),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice Question (MCQ)'), ('multiple_select', 'Multiple Select (Checkbox)'), ('true_false', 'True / False'), ('fill_blank', 'Fill in the Blank'), ('code_output', 'Code Output Prediction'), ('find_error', 'Find the Error'), ('debug_code', 'Debug the Code'), ('arrange_code', 'Arrange the Code (Drag & Drop)'), ('match_following', 'Match the Following Concepts'), ('drag_drop_blank', 'Drag and Drop Answer'), ('code_completion', 'Code Completion'), ('scenario_based', 'Scenario Based Question'), ('order_sequence', 'Order / Sequence Steps'), ('identify_output', 'Identify Complex Output'), ('predict_variable', 'Predict Variable Value'), ('code_ordering', 'Code Ordering'), ('diagram_question', 'Image / Diagram Based Question'), ('short_answer', 'Short Answer'), ('code_comparison', 'Code Comparison'), ('mini_challenge', 'Mini Coding Challenge')], default='mcq', max_length=30),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quizzes.quiz'),
        ),
    ]
