# Generated by Django 6.1.1 on 2026-10-06 05:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('level', models.CharField(choices=[('beginner', 'Beginner Level'), ('intermediate', 'Intermediate Level'), ('advanced', 'Advanced Level')], default='beginner', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('icon', models.CharField(default='fa-book', help_text='FontAwesome icon class, e.g. fa-code, fa-rocket', max_length=60)),
                ('order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name_plural': 'Tutorial Categories',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('summary', models.TextField(help_text='Brief 1-2 sentence overview for cards and meta description')),
                ('content', models.TextField(help_text='Main explanation in Markdown or HTML')),
                ('syntax', models.TextField(blank=True, default='', help_text='Syntax explanation or template')),
                ('code_example', models.TextField(blank=True, default='', help_text='Primary Python code example')),
                ('expected_output', models.TextField(blank=True, default='', help_text='Expected output of code_example')),
                ('important_notes', models.TextField(blank=True, default='', help_text='Important points or gotchas')),
                ('common_mistakes', models.TextField(blank=True, default='', help_text='Common pitfalls and mistakes to avoid')),
                ('real_world_example', models.TextField(blank=True, default='', help_text='Practical industry or real-world use case')),
                ('practice_code', models.TextField(blank=True, default='', help_text='Starter code for Try It Yourself editor')),
                ('estimated_read_time', models.PositiveIntegerField(default=5, help_text='Estimated reading time in minutes')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorials', to='tutorials.tutorialcategory')),
            ],
            options={
                'ordering': ['category__order', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TutorialProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_visited_at', models.DateTimeField(auto_now=True)),
                ('tutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='tutorials.tutorial')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorial_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'tutorial')},
            },
        ),
    ]
